# Use an official Python runtime as a parent image
FROM python:3

# Set the working directory to /app
WORKDIR /app

# Define environment variable
ENV DOCKER_API_VERSION 1.39

# Run app.py when the container launches
CMD ["python", "app.py"]
