# Generated by Django 2.1.3 on 2018-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioninstance',
            name='retorts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='solutioninstance',
            name='solution',
            field=models.TextField(null=True),
        ),
    ]
