# Generated by Django 2.1.3 on 2018-12-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutioninstance',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
