# Generated by Django 2.1.3 on 2018-12-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_solutioninstance_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutioninstance',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
