# Generated by Django 2.1.3 on 2019-01-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181221_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionInstance',
            new_name='Solution',
        ),
    ]
