# Generated by Django 2.1.3 on 2018-12-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181213_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutioninstance',
            old_name='retorts',
            new_name='reports',
        ),
    ]
