# Generated by Django 2.1.3 on 2019-01-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190115_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='language',
        ),
    ]
